### PR TITLE
Fix PVC latency metrics by preserving spec fields

### LINKED ISSUE #1112: [BUG] storageClass in pvcLatencyMeasurement metrics always Unknown
# Bug Description

## **Output of `kube-burner` version**

$ kube-burner version
Version: 2.2.2
Git Commit: 30914ef30240bba573bf70d89dd1cf3891462e53
Build Date: 2026-01-23T21:59:34Z
Go Version: go1.23.12
OS/Arch: linux amd64

## **Describe the bug**

pvcLatency metrics value storageClass is always null, ie:

```json
[
  {
    "timestamp": "2026-02-02T20:56:59.456993844Z",
    "pendingLatency": 7,
    "bindingLatency": 5636,
    "lostLatency": 0,
    "uuid": "c051cfb1-a45d-4a8f-8702-b88127081a38",
    "pvcName": "pod-job-pvc-pvc-1-0",
    "jobName": "pod-job-pvc",
    "namespace": "pod-job-pvc",
    "metricName": "pvcLatencyMeasurement",
    "size": "0",
    "storageClass": "unknown",
    "jobIteration": 0,
    "replica": 1,
    "metadata": null
  }
]
```

## **To Reproduce**

This behavior was observed on the latest version of kube-burner using the following manifests:

pod-job-pvc.yml

```yaml
---
global:
  gc: false
  gcMetrics: true
  deletionStrategy: default
  measurements:
   - name: jobLatency
   - name: pvcLatency
metricsEndpoints:
  - indexer:
      type: local
jobs:
  - name: pod-job-pvc
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: pod-job-pvc
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pvc.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-ssd-csi
          storageSize: 1Gi

      - objectTemplate: templates/job.yml
        replicas: 1
        inputVars:
          containerImage: fedora
```

job.yml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.JobName}}-{{.Replica}}-{{.Iteration}}
  labels:
    name: pod-job
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: hello-world
        image: {{.containerImage}}
        command: ["df"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{.JobName}}-pvc-{{.Replica}}-{{.Iteration}}
      restartPolicy: Never
```

pvc.yml

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.JobName}}-pvc-{{.Replica}}-{{.Iteration}}
  labels:
    name: pod-job
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.storageClassName}}
  resources:
    requests:
      storage: {{.storageSize}}
```

1. create these files
2. update pod-job-pvc.yml with a valid storageClass name
3. run kube-burner -c pod-job-pvc.yml

## **Expected behavior**

storageClass is defined in metrics

## **Screenshots or output**

```bash
$ kube-burner --log-level debug init -c pod-job-pvc.yml 
time="2026-02-02 20:56:59" level=info msg="📁 Creating local indexer: indexer-0" file="metrics.go:67"
time="2026-02-02 20:56:59" level=info msg="🔥 Starting kube-burner (2.2.2@30914ef30240bba573bf70d89dd1cf3891462e53) with UUID c051cfb1-a45d-4a8f-8702-b88127081a38" file="job.go:85"
time="2026-02-02 20:56:59" level=debug msg="pod-job-pvc: job.MaxWaitTimeout is zero, override by timeout: 4h0m0s" file="job.go:351"
time="2026-02-02 20:56:59" level=debug msg="pod-job-pvc: QPS: 300" file="job.go:361"
time="2026-02-02 20:56:59" level=debug msg="pod-job-pvc: Burst: 300" file="job.go:368"
time="2026-02-02 20:56:59" level=debug msg="Preparing create job: pod-job-pvc" file="create.go:57"
time="2026-02-02 20:56:59" level=debug msg="Rendering template: templates/pvc.yml" file="create.go:63"
time="2026-02-02 20:56:59" level=debug msg="Job pod-job-pvc: 1 iterations with 1 PersistentVolumeClaim replicas (object 1/1 from template)" file="create.go:101"
time="2026-02-02 20:56:59" level=debug msg="Rendering template: templates/job.yml" file="create.go:63"
time="2026-02-02 20:56:59" level=debug msg="Job pod-job-pvc: 1 iterations with 1 Job replicas (object 1/1 from template)" file="create.go:101"
time="2026-02-02 20:56:59" level=info msg="Initializing measurements for job: pod-job-pvc" file="factory.go:104"
time="2026-02-02 20:56:59" level=info msg="Registered measurement: jobLatency" file="factory.go:139"
time="2026-02-02 20:56:59" level=info msg="Registered measurement: pvcLatency" file="factory.go:139"
time="2026-02-02 20:56:59" level=info msg="Creating batch/v1, Resource=jobs latency watcher for pod-job-pvc using selector [kube-burner.io/runid=521c6144-3fa6-47e1-b4ae-ccab3638a2c3]" file="base_measurement.go:79"
time="2026-02-02 20:56:59" level=info msg="Creating /v1, Resource=persistentvolumeclaims latency watcher for pod-job-pvc using selector [kube-burner.io/runid=521c6144-3fa6-47e1-b4ae-ccab3638a2c3]" file="base_measurement.go:79"
time="2026-02-02 20:56:59" level=info msg="Triggering job: pod-job-pvc" file="job.go:115"
time="2026-02-02 20:56:59" level=info msg="Cleaning up previous runs" file="job.go:118"
time="2026-02-02 20:56:59" level=debug msg="Created namespace: pod-job-pvc" file="namespaces.go:53"
time="2026-02-02 20:56:59" level=debug msg="Creating object replicas from iteration 0" file="create.go:140"
time="2026-02-02 20:56:59" level=debug msg="Created PersistentVolumeClaim/pod-job-pvc-pvc-1-0 in namespace pod-job-pvc" file="create.go:354"
time="2026-02-02 20:56:59" level=debug msg="PVC pod-job-pvc-pvc-1-0 is pending" file="pvc_latency.go:135"
time="2026-02-02 20:57:00" level=debug msg="Created Job/pod-job-pvc-1-0 in namespace pod-job-pvc" file="create.go:354"
time="2026-02-02 20:57:00" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:260"
time="2026-02-02 20:57:00" level=debug msg="Waiting for pvcs in ns pod-job-pvc to be Bound" file="waiters.go:178"
time="2026-02-02 20:57:01" level=debug msg="Waiting for pvcs in ns pod-job-pvc to be Bound" file="waiters.go:178"
time="2026-02-02 20:57:02" level=debug msg="Waiting for pvcs in ns pod-job-pvc to be Bound" file="waiters.go:178"
time="2026-02-02 20:57:03" level=debug msg="Waiting for pvcs in ns pod-job-pvc to be Bound" file="waiters.go:178"
time="2026-02-02 20:57:04" level=debug msg="Waiting for pvcs in ns pod-job-pvc to be Bound" file="waiters.go:178"
time="2026-02-02 20:57:05" level=debug msg="PVC pod-job-pvc-pvc-1-0 is bound" file="pvc_latency.go:141"
time="2026-02-02 20:57:05" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:06" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:07" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:08" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:09" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:10" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:11" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:12" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:13" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:14" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:15" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:16" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:17" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:18" level=debug msg="Waiting for jobs in ns pod-job-pvc to be ready" file="waiters.go:316"
time="2026-02-02 20:57:18" level=debug msg="Status verified for object Job/pod-job-pvc-1-0" file="waiters.go:321"
time="2026-02-02 20:57:18" level=info msg="Actions in namespace pod-job-pvc completed" file="waiters.go:77"
time="2026-02-02 20:57:18" level=info msg="Verifying created objects" file="utils.go:161"
time="2026-02-02 20:57:18" level=debug msg="persistentvolumeclaims found: 1 Expected: 1" file="utils.go:205"
time="2026-02-02 20:57:18" level=debug msg="jobs found: 1 Expected: 1" file="utils.go:205"
time="2026-02-02 20:57:18" level=info msg="Job pod-job-pvc took 19s" file="job.go:188"
time="2026-02-02 20:57:18" level=info msg="Stopping measurement: pvcLatency" file="factory.go:168"
time="2026-02-02 20:57:18" level=info msg="pod-job-pvc: Pending 99th: 7ms max: 7ms avg: 7ms" file="base_measurement.go:127"
time="2026-02-02 20:57:18" level=info msg="pod-job-pvc: Bound 99th: 5636ms max: 5636ms avg: 5636ms" file="base_measurement.go:127"
time="2026-02-02 20:57:18" level=info msg="pod-job-pvc: Lost 99th: 0ms max: 0ms avg: 0ms" file="base_measurement.go:127"
time="2026-02-02 20:57:18" level=info msg="Stopping measurement: jobLatency" file="factory.go:168"
time="2026-02-02 20:57:18" level=info msg="pod-job-pvc: StartTime 99th: 1000ms max: 1000ms avg: 1000ms" file="base_measurement.go:127"
time="2026-02-02 20:57:18" level=info msg="pod-job-pvc: Complete 99th: 18000ms max: 18000ms avg: 18000ms" file="base_measurement.go:127"
time="2026-02-02 20:57:18" level=info msg="Indexing collected data from measurement: jobLatency" file="factory.go:180"
time="2026-02-02 20:57:18" level=info msg="Indexing metric jobLatencyMeasurement" file="base_measurement.go:150"
time="2026-02-02 20:57:18" level=debug msg="Indexing [1] documents: jobLatencyMeasurement" file="base_measurement.go:154"
time="2026-02-02 20:57:18" level=info msg="File collected-metrics/jobLatencyMeasurement-pod-job-pvc.json created with 1 documents" file="base_measurement.go:159"
time="2026-02-02 20:57:18" level=info msg="Indexing metric jobLatencyQuantilesMeasurement" file="base_measurement.go:150"
time="2026-02-02 20:57:18" level=debug msg="Indexing [2] documents: jobLatencyQuantilesMeasurement" file="base_measurement.go:154"
time="2026-02-02 20:57:18" level=info msg="File collected-metrics/jobLatencyQuantilesMeasurement-pod-job-pvc.json created with 2 documents" file="base_measurement.go:159"
time="2026-02-02 20:57:18" level=info msg="Indexing collected data from measurement: pvcLatency" file="factory.go:180"
time="2026-02-02 20:57:18" level=info msg="Indexing metric pvcLatencyMeasurement" file="base_measurement.go:150"
time="2026-02-02 20:57:18" level=debug msg="Indexing [1] documents: pvcLatencyMeasurement" file="base_measurement.go:154"
time="2026-02-02 20:57:18" level=info msg="File collected-metrics/pvcLatencyMeasurement-pod-job-pvc.json created with 1 documents" file="base_measurement.go:159"
time="2026-02-02 20:57:18" level=info msg="Indexing metric pvcLatencyQuantilesMeasurement" file="base_measurement.go:150"
time="2026-02-02 20:57:18" level=debug msg="Indexing [3] documents: pvcLatencyQuantilesMeasurement" file="base_measurement.go:154"
time="2026-02-02 20:57:18" level=info msg="File collected-metrics/pvcLatencyQuantilesMeasurement-pod-job-pvc.json created with 3 documents" file="base_measurement.go:159"
time="2026-02-02 20:57:18" level=info msg="Indexing job summaries" file="metadata.go:48"
time="2026-02-02 20:57:18" level=info msg="File collected-metrics/jobSummary.json created with 1 documents" file="metadata.go:65"
time="2026-02-02 20:57:18" level=info msg="Finished execution with UUID: c051cfb1-a45d-4a8f-8702-b88127081a38" file="job.go:260"
time="2026-02-02 20:57:18" level=info msg="👋 Exiting kube-burner c051cfb1-a45d-4a8f-8702-b88127081a38" file="kube-burner.go:89"
$ ls -l collected-metrics/
total 20
-rw-rw-r-- 1 igou igou 298 Feb  2 20:57 jobLatencyMeasurement-pod-job-pvc.json
-rw-rw-r-- 1 igou igou 551 Feb  2 20:57 jobLatencyQuantilesMeasurement-pod-job-pvc.json
-rw-rw-r-- 1 igou igou 651 Feb  2 20:57 jobSummary.json
-rw-rw-r-- 1 igou igou 352 Feb  2 20:57 pvcLatencyMeasurement-pod-job-pvc.json
-rw-rw-r-- 1 igou igou 769 Feb  2 20:57 pvcLatencyQuantilesMeasurement-pod-job-pvc.json
$ cat collected-metrics/pvcLatencyMeasurement-pod-job-pvc.json | jq
[
  {
    "timestamp": "2026-02-02T20:56:59.456993844Z",
    "pendingLatency": 7,
    "bindingLatency": 5636,
    "lostLatency": 0,
    "uuid": "c051cfb1-a45d-4a8f-8702-b88127081a38",
    "pvcName": "pod-job-pvc-pvc-1-0",
    "jobName": "pod-job-pvc",
    "namespace": "pod-job-pvc",
    "metricName": "pvcLatencyMeasurement",
    "size": "0",
    "storageClass": "unknown",
    "jobIteration": 0,
    "replica": 1,
    "metadata": null
  }
]
```

## **Additional context**

The Size metrics also appears to be not logged properly, as it's "0"

### PR DESCRIPTION
**Pull request by Nesar976**
## Type of change
- Bug fix

## Description
This PR fixes an issue where PVC latency metrics reported `storageClass` as `unknown` and `size` as `0` even when PVCs were created and bound correctly.

The root cause was that the PVC transform logic preserved only metadata and status fields, dropping required spec fields during updates. This change ensures that relevant spec fields are preserved and that missing metric values are populated from the PVC object when necessary.

No API changes are introduced, and existing behavior outside PVC latency metrics remains unchanged.

## Related Tickets & Documents
Fixes  #1112

### CODE REVIEW

**Comment by rsevilla87** [comment]
To be fixed by https://github.com/kube-burner/kube-burner/pull/1086

**Comment by ygalblum** [comment]
> To be fixed by #1086

But why wait for it? This PR comes to fix a specific problem. The other one fixes it as a side effect

**Comment by Nesar976** [comment]
Hi @ygalblum ,
Thanks for the clarification. If there are any changes or improvements needed from my side, please let me know—I’m happy to update the PR accordingly.

**Review by rsevilla87 — DISMISSED** [review]

File: pkg/measurements/pvc_latency.go [hunk 1]
```diff
@@ -128,8 +128,13 @@ func (p *pvcLatency) handleUpdatePVC(obj any) {
 	if value, exists := p.Metrics.Load(string(pvc.UID)); exists {
 		pm := value.(pvcMetric)
 		log.Tracef("handleUpdatePVC: PVC: [%s], Version: [%s], Phase: [%s]", pvc.Name, pvc.ResourceVersion, pvc.Status.Phase)
+		if pm.StorageClass == "" || pm.StorageClass == "unknown" {
+			pm.StorageClass = getStorageClassName(*pvc)
+		}
+		if pm.Size == "" || pm.Size == "0" {
+			pm.Size = pvc.Spec.Resources.Requests.Storage().String()
+		}
```
Comment (rsevilla87) [inline pkg/measurements/pvc_latency.go]: I think this is not necessary, these fields are already set in handleCreatePVC

Comment (Nesar976) [reply pkg/measurements/pvc_latency.go]: Thanks for the review. I’ve removed the redundant PVC spec handling and pushed the update. Please let me know if anything else needs to be adjusted.

**Comment by Nesar976** [comment]
Hi @rsevilla87 ,
Thanks for the review. I’ve removed the redundant PVC spec handling and pushed the update. Please let me know if anything else needs to be adjusted.

**Comment by Nesar976** [comment]
Hi @rsevilla87, following up on this PR. All feedback has been addressed and checks are passing.
Please let me know if anything else is needed from my side. Thanks!
