### PR TITLE
Reduce memory footprint for measurements

### LINKED ISSUE #1080: [BUG] Very large kube-burner memory usage for node-density-cni 200 ppn with 750 nodes
# Bug Description

## **Output of `kube-burner` version**
```
KUBE_BURNER_VERSION=1.9.2
```

## **Describe the bug**

When running a large scale node-density-cni test (750 node OCP cluster) in prow, the CI container running kube-burner was killed because it went over its memory allocation limit:
```
 ERRO[2026-01-21T06:25:09Z] Some steps failed:                           
ERRO[2026-01-21T06:25:09Z] 
  * could not run steps: step ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni failed: ["ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni" test steps failed: "ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni" pod "ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni-openshift-qe-node-density-cni" failed: could not watch pod: the pod ci-op-wn7mhtrb/ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni-openshift-qe-node-density-cni failed after 2h42m1s (failed containers: test): Evicted The node was low on resource: memory. Threshold quantity: 100Mi, available: 95044Ki. Container test was using 25712144Ki, request is 18281250Ki, has larger consumption of memory. 
Container test exited with code 137, reason Error
```

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/73587/rehearse-73587-pull-ci-openshift-ovn-kubernetes-master-ovncore-perfscale-aws-ovn-xlarge-node-density-cni/2013742347891773440#1:build-log.txt%3A411

## **To Reproduce**

Set up an OCP 750 node cluster, run node-density-cni, e.g.
```
/tmp/kube-burner-ocp node-density-cni --log-level=info --qps=20 --burst=20 --gc=false --uuid e51ad3fe-0c39-45ca-911c-53c4500d428c --churn-duration=20m --service-latency --gc=false --gc-metrics=false --pods-per-node=200 --namespaced-iterations=true --iterations-per-namespace=1000 --profile-type=both --pprof=false --es-server=https://XXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXX@search-xxxxxx-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ --es-index=ripsaw-kube-burner
```

## **Expected behavior**

kube-burner shouldn't use an excessive amount of memory (it was killed at ~25Gi).

## **Screenshots or output**

The CI infra killed the pod running kube-burner at this point:
```
 time="2026-01-21 01:01:34" level=info msg="Triggering job: node-density-cni" file="job.go:115"
time="2026-01-21 01:01:34" level=info msg="Cleaning up previous runs" file="job.go:118"
time="2026-01-21 01:01:34" level=info msg="Churning enabled" file="job.go:122"
time="2026-01-21 01:01:34" level=info msg="Churn cycles: 0" file="job.go:123"
time="2026-01-21 01:01:34" level=info msg="Churn duration: 20m0s" file="job.go:124"
time="2026-01-21 01:01:34" level=info msg="Churn percent: 10" file="job.go:125"
time="2026-01-21 01:01:34" level=info msg="Churn delay: 2m0s" file="job.go:126"
time="2026-01-21 01:01:34" level=info msg="Churn type: objects" file="job.go:127"
time="2026-01-21 01:18:43" level=info msg="6862/68622 iterations completed" file="create.go:134"
time="2026-01-21 01:35:52" level=info msg="13724/68622 iterations completed" file="create.go:134"
time="2026-01-21 01:53:01" level=info msg="20586/68622 iterations completed" file="create.go:134"
time="2026-01-21 02:10:11" level=info msg="27448/68622 iterations completed" file="create.go:134"
time="2026-01-21 02:27:20" level=info msg="34310/68622 iterations completed" file="create.go:134"
time="2026-01-21 02:44:29" level=info msg="41172/68622 iterations completed" file="create.go:134"
time="2026-01-21 03:01:39" level=info msg="48034/68622 iterations completed" file="create.go:134"
time="2026-01-21 03:18:48" level=info msg="54896/68622 iterations completed" file="create.go:134"
time="2026-01-21 03:35:57" level=info msg="61758/68622 iterations completed" file="create.go:134"
received signal 15, forwarding 
```

with

```
  * could not run steps: step ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni failed: ["ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni" test steps failed: "ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni" pod "ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni-openshift-qe-node-density-cni" failed: could not watch pod: the pod ci-op-wn7mhtrb/ovncore-XXXXXXXXX-aws-ovn-xlarge-node-density-cni-openshift-qe-node-density-cni failed after 2h42m1s (failed containers: test): Evicted The node was low on resource: memory. Threshold quantity: 100Mi, available: 95044Ki. Container test was using 25712144Ki, request is 18281250Ki, has larger consumption of memory. 
Container test exited with code 137, reason Error
```

### PR DESCRIPTION
**Pull request by avasilevskii**
## Type of change

- Bug fix
- Optimization

## Description
This PR introduces TransformFunc in measurements Informer to reduce memory footprint for pods, jobs, nodes and events.

## Related Tickets & Documents

- Related Issue #1080
- Closes #1080

### CODE REVIEW

**Comment by avasilevskii** [comment]
Some quick-and-dirty micro-benchmarks with pod and event objects sampled from a real cluster showed quite promising memory reduction:
```
=== Transform Function Memory Comparison ===
Testing with 3000 pods

1. WITHOUT Transform (full pods): 36.08 MB (12.31 KB/pod)
2. WITH Transform (minimal pods): 4.02 MB (1.37 KB/pod)

=== Results ===
Memory saved by transform: 32.06 MB (88.9%)
```

File: pkg/measurements/pod_latency.go
Comment (rsevilla87) [inline pkg/measurements/pod_latency.go:234]: I wonder if we can add a Transform function in listers as well

Comment (rsevilla87) [reply pkg/measurements/pod_latency.go:234]: iirc, there's at least another one in service_latency.go

Comment (avasilevskii) [reply pkg/measurements/pod_latency.go:234]: Do you mean a transform func to filter for relevant events for the pods kube-burner creates only as opposed to current `p.eventLister.List(labels.Everything())`?

**Comment by avasilevskii** [comment]
Ran a few more tests with the sample kubelet-density-cni workload and 5000 iterations, which results in 10000 pods: the patched kube-burner requires around 50MB RSS as opposed to 180MB in the main branch. The actual memory reduction is not as dramatical as 89% observed in the micro-benchmark, but still north of 70%.

Also confirmed that with the latest changes (remove unnecessary type casting), kube-burner is calculating pod and job latencies correctly:
```
time="2026-01-22 11:22:01" level=info msg="Stopping measurement: podLatency" file="factory.go:168"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: Ready 99th: 4000ms max: 4000ms avg: 1675ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: PodReadyToStartContainers 99th: 2000ms max: 2000ms avg: 915ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: ContainersStarted 99th: 1466ms max: 1495ms avg: 1001ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: PodScheduled 99th: 0ms max: 0ms avg: 0ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: ContainersReady 99th: 4000ms max: 4000ms avg: 1675ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: Initialized 99th: 1000ms max: 1000ms avg: 15ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="Stopping measurement: jobLatency" file="factory.go:168"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: Complete 99th: 22000ms max: 22000ms avg: 18450ms" file="base_measurement.go:127"
time="2026-01-22 11:22:01" level=info msg="kubelet-density-cni: StartTime 99th: 5000ms max: 5000ms avg: 800ms" file="base_measurement.go:127"
```

File: pkg/measurements/pod_latency.go [hunk 1]
```diff
@@ -223,6 +223,9 @@ func (p *podLatency) Start(measurementWg *sync.WaitGroup) error {
 		},
 	)
 	eventInformer := cache.NewSharedIndexInformer(lw, &corev1.Event{}, 0, cache.Indexers{})
+	if err := eventInformer.SetTransform(EventTransformFunc()); err != nil {
```
Comment (rsevilla87) [inline pkg/measurements/pod_latency.go]: So it seems like you implemented a transform function for the lister informer, nice!

**Comment by avasilevskii** [comment]
Added TranformFunc for all other *_latency measurements, tested locally with job, pod and service latency:
```
time="2026-01-22 12:08:44" level=info msg="Stopping measurement: jobLatency" file="factory.go:168"
time="2026-01-22 12:08:44" level=info msg="kubelet-density-cni: StartTime 99th: 5000ms max: 5000ms avg: 790ms" file="base_measurement.go:127"
time="2026-01-22 12:08:44" level=info msg="kubelet-density-cni: Complete 99th: 22000ms max: 22000ms avg: 18420ms" file="base_measurement.go:127"
time="2026-01-22 12:08:44" level=info msg="Stopping measurement: serviceLatency" file="factory.go:168"
time="2026-01-22 12:08:44" level=info msg="Deleting 1 namespaces with label: kubernetes.io/metadata.name=kube-burner-service-latency" file="namespaces.go:65"
time="2026-01-22 12:08:50" level=info msg="serviceLatency: kubelet-density-cni: Ready 99th: 1076 ms max: 1141 ms avg: 472 ms" file="service_latency.go:246"
time="2026-01-22 12:08:50" level=info msg="Stopping measurement: podLatency" file="factory.go:168"
time="2026-01-22 12:08:50" level=info msg="kubelet-density-cni: Initialized 99th: 0ms max: 0ms avg: 0ms" file="base_measurement.go:127"
time="2026-01-22 12:08:50" level=info msg="kubelet-density-cni: Ready 99th: 3000ms max: 3000ms avg: 1595ms" file="base_measurement.go:127"
time="2026-01-22 12:08:50" level=info msg="kubelet-density-cni: PodReadyToStartContainers 99th: 2000ms max: 2000ms avg: 925ms" file="base_measurement.go:127"
time="2026-01-22 12:08:50" level=info msg="kubelet-density-cni: ContainersStarted 99th: 1432ms max: 1448ms avg: 980ms" file="base_measurement.go:127"
time="2026-01-22 12:08:50" level=info msg="kubelet-density-cni: PodScheduled 99th: 0ms max: 0ms avg: 0ms" file="base_measurement.go:127"
time="2026-01-22 12:08:50" level=info msg="kubelet-density-cni: ContainersReady 99th: 3000ms max: 3000ms avg: 1595ms" file="base_measurement.go:127"
```

File: pkg/measurements/transforms.go [hunk 2]
```diff
@@ -0,0 +1,352 @@
...
+		u, ok := obj.(*unstructured.Unstructured)
+		if !ok {
+			return obj, nil
+		}
+
+		minimal := createMinimalUnstructured(u, defaultMetadataTransformOpts())
+
+		// Preserve only kube-burner annotation if present
+		if annotations := u.GetAnnotations(); annotations != nil {
+			if val, exists := annotations["kube-burner.io/service-latency"]; exists {
```
Comment (ygalblum) [inline pkg/measurements/transforms.go]: Isn't there a `const` defined fro this label?

**Review by ygalblum — COMMENTED** [review]
Regarding file structure, I think each resource specific transformer should be implemented in the file that uses it (e.g. `DataVolumeTransformFunc` in `datavolume_latency.go`)

File: pkg/measurements/transforms.go (hunk 2 above)
Comment (rsevilla87) [reply pkg/measurements/transforms.go]: nope :(, I probably didn't add it because it was used in one line.

File: pkg/measurements/service_latency.go
Comment (rsevilla87) [inline pkg/measurements/service_latency.go:1]: These 2 listers still miss a TransformFunction https://github.com/avasilevskii/kube-burner/blob/a0afb206cf99c0336ef3e285dab498aab9041db0/pkg/measurements/service_latency.go#L203-L204

File: pkg/measurements/transforms.go (hunk 2 above)
Comment (ygalblum) [reply pkg/measurements/transforms.go]: So, please let's add it. It's best if we have all `kube-burner.io/*` labels defined in one place

File: pkg/measurements/service_latency.go
Comment (avasilevskii) [reply pkg/measurements/service_latency.go:1]: Added serviceTypedTransformFunc and endpointSliceTransformFunc
