### PR TITLE
Replace endpoints references by endpointslices

### LINKED ISSUE #1011: [BUG] v1 Endpoints is deprecated in v1.33+; use discovery.k8s.io/v1 EndpointSlice
# Bug Description
v1 Endpoints is deprecated in v1.33+; use discovery.k8s.io/v1 EndpointSlice 

## **Output of `kube-burner` version**
1.7.6@230950f287b17ca27860a417c60c81f03675ace4

## **Describe the bug**
Currently getting lots of warnings in the log output : 

```
W1027 20:04:55.674095 507 warnings.go:70] v1 Endpoints is deprecated in v1.33+; use discovery.k8s.io/v1 EndpointSlice
W1027 20:05:55.673735 507 warnings.go:70] v1 Endpoints is deprecated in v1.33+; use discovery.k8s.io/v1 EndpointSlice
```

Just starting an issue now before Endpoints are removed.

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- Bug fix
- Optimization

## Description

Replace the deprecated endpoints references by endpointslices in the `serviceLatency` measurement

## Related Tickets & Documents

- Related Issue #
- Closes #1011

### CODE REVIEW

File: pkg/measurements/service_latency.go [hunk 1]
```diff
@@ -171,19 +168,22 @@ func (s *serviceLatency) handleCreateSvc(obj any) {
...
 		types.SvcLatencyNs,
 		types.SvcLatencyCheckerName,
-		"quay.io/cloud-bulldozer/fedora-nc:latest",
+		"quay.io/kube-burner/fedora-nc:latest",
 		[]string{"sleep", "inf"},
 	); err != nil {
 		return err
 	}
-
+	if s.svcLatencyChecker, err = mutil.NewSvcLatencyChecker(s.ClientSet, *s.RestConfig); err != nil {
```
Comment (rsevilla87) [inline pkg/measurements/service_latency.go:184]: Moving the instantiation of svcLatencyChecker here prevents instantiating a new replica of it whenever a service is created.

**Review by vishnuchalla — APPROVED** [review]
lgtm, cc @venkataanil  ^^
