### PR TITLE
Fix unsafe access to labels map to avoid a panic

### LINKED ISSUE #534: [BUG] Panic when running `init` (sometimes)
# Bug Description

## **Output of `kube-burner` version**

1.8.0

## **Describe the bug**

Sometimes when running `init` `kube-burner` panics (see attached file). It's unclear what triggers it, but it seems that it's triggered more often when there's nothing to clean up from the previous run (so there's no deletion step prior to creating resources).

This did not occur with the `v1.7.13` as far as I can tell.

[gopanic.txt](https://github.com/cloud-bulldozer/kube-burner/files/13598581/gopanic.txt)

## **To Reproduce**

1. Run/rerun `init` several times, try not cleaning up sometimes.

## **Expected behavior**

No panic.

## **Screenshots or output**

See attached filed

### PR DESCRIPTION
**Pull request by diversario**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Make a per-goroutine copy of the `label` map to avoid concurrent read/writes to it.

## Related Tickets & Documents

- Closes #534 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

File: pkg/burner/create.go [hunk 1]
```diff
@@ -204,7 +204,14 @@ func (ex *Executor) generateNamespace(iteration int) string {
 
 func (ex *Executor) replicaHandler(labels map[string]string, obj object, ns string, iteration int, replicaWg *sync.WaitGroup) {
 	var wg sync.WaitGroup
+
 	for r := 1; r <= obj.Replicas; r++ {
+		// make a copy of the copiedLabels map
```
Comment (Nick-Triller) [inline pkg/burner/create.go:209]:
```suggestion
		// make a copy of the labels map for each goroutine to prevent panic from concurrent read and write
```

File: pkg/burner/create.go [hunk 2]
```diff
@@ -204,7 +204,14 @@ func (ex *Executor) generateNamespace(iteration int) string {
 
 func (ex *Executor) replicaHandler(labels map[string]string, obj object, ns string, iteration int, replicaWg *sync.WaitGroup) {
 	var wg sync.WaitGroup
+
 	for r := 1; r <= obj.Replicas; r++ {
+		// make a copy of the labels map for each goroutine to prevent panic from concurrent read and write
+		copiedLabels := make(map[string]string)
+		for k, v := range labels {
+			copiedLabels[k] = v
+		}
```
Comment (rsevilla87) [inline pkg/burner/create.go:213]: Rather than using a new variable, `copiedLabels`, why don't you pass the variable `labels` as argument to the goroutine below?

File: pkg/burner/create.go [hunk 3]
```diff
@@ -204,7 +204,14 @@ func (ex *Executor) generateNamespace(iteration int) string {
...
+
 		wg.Add(1)
 		go func(r int) {
```
Comment (rsevilla87) [inline pkg/burner/create.go:216]:
```suggestion
		go func(r int, labels map[string]string) {
```

File: pkg/burner/create.go (hunk 2 above)
Comment (ntriller-plaid) [reply pkg/burner/create.go:213]: Just to clarify, are you saying you would prefer this?
```golang
# Shadow label variable with copy
labels := make(map[string]string)
for k, v := range labels {
  copiedLabels[k] = v
}
```
Or are you asking why we create a copy? If the latter, the copy fixes an occasional panic in kube burner that occurs because the go routines below are all using the same `labels` map currently. The goroutines iterate over the map as well as write to the map. If one goroutine happens to iterate over the map at the same time another goroutine writes to the map, kube burner panics.

File: pkg/burner/create.go (hunk 3 above)
Comment (rsevilla87) [reply pkg/burner/create.go:216]: If you pass the labels variable as argument, a new copy of `labels`  is actually passed to the goroutine, similar of what we're already doing with `r`

https://github.com/cloud-bulldozer/kube-burner/blob/c75cbe529b3aed8278292d863d4b8ba1f69f0201/pkg/burner/create.go#L205-L209

**Comment by rsevilla87** [comment]
Hey, any plans to update this PR?, if not I can file a PR myself to fix this bug

**Comment by diversario** [comment]
> Hey, any plans to update this PR?, if not I can file a PR myself to fix this bug

Will update now. BTW, on line 242 https://github.com/cloud-bulldozer/kube-burner/pull/536/files#diff-76e5989cd670c9a6f994b653f5f41d8eacf7d309dc9074b48f9754bbac133018R242 there's `json.Marshal(newObject.Object)` that's unused - should I remove that?

File: pkg/burner/create.go (hunk 3 above)
Comment (ntriller-plaid) [reply pkg/burner/create.go:216]: Based on this quick test, I do not thing the suggestion works as expected:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	theMap := make(map[string]int)
	go func(m map[string]int) {
		for {
			// Write to map
			m["pi"] = 3
		}
	}(theMap)
	go func(m map[string]int) {
		// Iterate over map
		for {
			for k, v := range m {
				// do nothing
				if k == "" || v == 0 {
					fmt.Println("should never happen")
				}
			}
		}
	}(theMap)
	time.Sleep(10)
}
```
Above code snippet errors with `fatal error: concurrent map iteration and map write`.

**Comment by rsevilla87** [comment]
> > Hey, any plans to update this PR?, if not I can file a PR myself to fix this bug
> 
> Will update now. BTW, on line 242 https://github.com/cloud-bulldozer/kube-burner/pull/536/files#diff-76e5989cd670c9a6f994b653f5f41d8eacf7d309dc9074b48f9754bbac133018R242 there's `json.Marshal(newObject.Object)` that's unused - should I remove that?

yes please, that's probably a typo

File: pkg/burner/create.go (hunk 3 above)
Comment (rsevilla87) [reply pkg/burner/create.go:216]: You're right!, just realized that maps are passed by reference and not by value...

Comment (rsevilla87) [reply pkg/burner/create.go:216]: using a mutex can fix the issue, but I think your initial approach is easier to understand, let's keep it :)
