### PR TITLE
fix(burner): fix objectOperations metric on early returns

### LINKED ISSUE #1101: Metric counter may be skipped on early error returns
Some code paths return early on error before incrementing: atomic.AddInt32(&ex.objectOperations, 1)

When this happens, failed attempts are not reflected in metrics, which can lead to under-counting and inaccurate reporting. This mainly affects metric accuracy and observability rather than functionality.

### PR DESCRIPTION
**Pull request by Nesar976**
## Type of change
- Bug fix

## Description
While working on the request creation flow, I noticed that the
`objectOperations` metric was not always being incremented when the
function returned early due to an error.

This change moves the metric increment to a deferred statement so it
is consistently recorded in all execution paths, avoiding missed
increments and preventing double counting.

Please let me know if any additional adjustments are needed.

Fixes #1101

### CODE REVIEW

File: pkg/burner/create.go [hunk 1]
```diff
@@ -301,6 +301,7 @@ func (ex *JobExecutor) waitForCompletion(iterationStart, iterationEnd int, ns st
 }
 
 func (ex *JobExecutor) createRequest(ctx context.Context, gvr schema.GroupVersionResource, ns string, obj *unstructured.Unstructured, timeout time.Duration) {
+	defer atomic.AddInt32(&ex.objectOperations, 1)
```
Comment (rsevilla87) [inline pkg/burner/create.go]: This is not valid, the requests can be retried due to RetryWithExponentialBackOff I think is better to place `atomic.AddInt32(&ex.objectOperations, 1)`  right after line 314

**Comment by Nesar976** [comment]
Hi @rsevilla87 Thanks for pointing this out. I’ve removed the defer and moved atomic.AddInt32(&ex.objectOperations, 1) right after line 314 inside the RetryWithExponentialBackOff callback as suggested.
